#!/bin/sh
use(){ for p in "$@"; do [ -x "mod/$p" ] || return; debug "loading module $p"; . "mod/$p"; done }
hook(){ debug "registering hook $2:$1"; hooks="$hooks\n$2:$1"; }

log(){ printf '\e[0;35m[\e[0m%s\e[0;35m]\e[0m %s\n' "${2:-info}" "$1"  >&2; }
warning() { printf '[\e[0;33m%s\e[0m] %s\n' "${2:-warning}" "$1" >&2; }
error() { printf '[\e[0;31m%s\e[0m] %s\n' "${2:-error}" "$1" >&2; }
debug(){ [ "$debug" = '1' ] && printf '\e[0;33m[\e[0m%s\e[0;33m]\e[0m %s\n' "${2:-debug}" "$1" >&2; }

alias _='cat<<\_'
alias __='cat<<__'
