#!/bin/sh
# mkweb v0.1; copyright 2021 Job79
# license: mit-license.org
HELP(){ printf "USAGE
	mkweb command [args...]

COMMANDS
	run [filter]		Generate changed files
	crun [filter]		Clean and generate files
	clean			Remove generated website files
"; }
RUN(){
	[ -x 'config' ] && . './config'
	$(find 'src' -type f \( -name "${2:-*}" ! -path '*_*' \) | while read -r in
	do
		out="out/${in#*/}"
		if [ -n "$2" ] || [ ! -f "$out" ] || [ "$( find "$in" -newer "$out" )" ]; then
			log "$in" 'run'
			outdir="${out%/*}"; [ ! -d "$outdir" ] && mkdir -p "$outdir"
			if [ -x "$in" ]; then . "./$in" > "$out"; else cp "$in" "$out"; fi
			(for h in $hooks; do ${h#*:} >&2; done)&
		fi
	done)
	[ -x 'publish' ] && . './publish'
}
CLEAN(){ log 'cleaned output folder'; rm -rf out; }

# LIB #
use(){ for p in "$@"; do [ -x "mod/$p" ] || continue; debug "loading module $p"; . "./mod/$p"; done }
hook(){ debug "registering hook $1:$2"; hooks="$(printf '%s\n' $hooks "$1:$2" | sort -n | tr '\n' ' ')"; }
include(){ [ -f "src/$1" ] && . "./src/$1"; }

log(){ printf '\e[0;35m[\e[0m%s\e[0;35m]\e[0m %s\n' "${2:-info}" "$1" >&2; }
warning() { printf '[\e[0;33m%s\e[0m] %s\n' "${2:-warning}" "$1" >&2; }
error() { printf '[\e[0;31m%s\e[0m] %s\n' "${2:-error}" "$1" >&2; }
debug(){ [ "$debug" = '1' ] && printf '\e[0;33m[\e[0m%s\e[0;33m]\e[0m %s\n' "${2:-debug}" "$1" >&2; }

alias _='cat<<\_'; alias __='cat<<__'

# RUN #
cd "$(dirname "$(realpath "$0")")" || exit;
debug='0'; PATH="./bin:$PATH"; exec 2>&1
case "$1" in
	run) RUN "$@" ;;
	crun) CLEAN; RUN "$@" ;;
	clean) CLEAN ;;
	*) HELP ;;
esac; exit 0
