#!/bin/sh
# mkweb v0.1; copyright 2021 Job79
# license: mit-license.org
HELP(){ printf "USAGE
	mkweb command [args...]

COMMANDS
	run [filter]		Generate website
	clean			Remove generated website files
	crun [filter]		Regenerate website
"; }
RUN(){
	[ -x 'config' ] && . './config'
	find 'src' -name "${1:-*}" -type f | while read -r in
	do
		out="out/${in#*/}"; outdir="${out%/*}"
		if [ ! -f "$out" ] || [ "$( find "$in" -newer "$out" )" ]; then
			log "$in" 'run'
			[ ! -d "$outdir" ] && mkdir -p "$outdir"
			if [ -x "$in" ]; then . "./$in" > "$out"; else cp "$in" "$out"; fi
			echo "$hooks" | sort -n | while read -r hook; do ${hook#*:}; done;
		fi
	done
	[ -x 'publish' ] && . './publish'
}
CLEAN(){ log 'cleaned output folder'; rm -rf out; }

cd "$(dirname "$(realpath "$0")")" || exit;
debug='1'; . './lib'
case "$1" in
	run) shift; RUN "$@" ;;
	clean) shift; CLEAN "$@" ;;
	crun) shift; CLEAN; RUN; "$@" ;;
	*) HELP ;;
esac
exit 0
