#!/bin/sh
# brotli compresses website files
#
# PARAMS
# $compression_filter list with extensions that should be compressed
# $brotli_compression_level compression level
if ! command -v brotli >/dev/null 2>&1; then
	err 'could not find brotli binary' 'brotli'
	return
fi

hook 'hook_brotli'
hook_brotli() {
	for ext in ${compression_filter:-html css js svg ico atom}; do
		[ "${out##*.}" = "$ext" ] || continue
		clevel="${brotli_compression_level:-Z}"
		dbg "$out; level: $clevel" 'brotli'
		brotli "-kf$clevel" "$out"
		return
	done
}
