#!/bin/sh
if ! command -v gzip >/dev/null 2>&1; then
	warning 'could not find gzip' 'brotli'
	return
fi

hook '9' 'hook_gzip'
hook_gzip() {
	gzip_compression_level="${gzip_compression_level:-9}"
	echo "${out##*.}" | grep -Eq "^(${compression_filter:-html|css|js})$" || return
	debug "compressing $out; level: $gzip_compression_level" 'gzip'
	gzip "-kf$gzip_compression_level" "$out"
}
