#!/bin/sh
# gzip compresses website files
#
# PARAMS
# $compression_filter list with extensions that should be compressed
# $gzip_compression_level compression level
if ! command -v gzip >/dev/null 2>&1; then
	err 'could not find gzip binary' 'gzip'
	return
fi

hook 'hook_gzip'
hook_gzip() {
	for ext in ${compression_filter:-html css js svg ico atom}; do
		[ "${out##*.}" = "$ext" ] || continue
		clevel="${gzip_compression_level:-9}"
		dbg "$out; level: $clevel" 'gzip'
		gzip "-kf$gzip_compression_level" "$out"
		return
	done
}
