#!/bin/sh
# minify (optimize) html, css, js, json, svg and xml files
#
# USAGE [ hook ]
#	install minify and invoke this module
#
# VARIABLES
#	minify_flags
#		flags for the minify application
#	minify_filter; default: html|css|js|json|svg|xml
#		list of targeted filetypes
if ! command -v minify >/dev/null 2>&1; then
	warning 'could not find minify binary; download: github.com/tdewolff/minify' 'minify'
	return
fi

hook '8' 'hook_minify'
hook_minify() {
	echo "${out##*.}" | grep -Eq "^(${minify_filter:-html|css|js|json|svg|xml})$" || return
	debug "optimizing $out" 'minify'
	minify "$out" --output "$out" $minify_flags
}
