#!/bin/sh
# minify website files
#
# PARAMS
# $minify_filter list with extensions that should be minified
# $minify_flags additional minify flags
if ! command -v minify >/dev/null 2>&1; then
	err "could not find minify binary; download: github.com/tdewolff/minify" 'minify'
	exit
fi

hook 'hook_minify'
hook_minify() {
	for ext in ${minify_filter:-html css js svg xml json}; do
		[ "${out##*.}" = "$ext" ] || continue
		dbg "$out" 'minify'
		minify "$out" --output "$out" $minify_flags
		return
	done
}
