#!/bin/sh
hook 'hook_templates' '500'
hook_templates() {(
	template="${template:-template}"
	[ ! -x "src/$template" ] && warning 'template file not found' 'templates' && return
	echo "${out##*.}" | grep -Eq "^(${template_filter:-html})$" || return

	debug "applying template to $out" 'templates'
	content="$(cat "$out")"
	. "./src/$template" > "$out"
)}
